/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import javax.swing.JOptionPane;

/**
 *
 * @author minam
 */
public class DeleteSupplier extends javax.swing.JFrame {

    /**
     * Creates new form DeleteSupplier
     */
    public DeleteSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deletesupplierbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deletesupplierIDtxt = new javax.swing.JTextField();
        exitdeletesupplierbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deletesupplierbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        deletesupplierbtn.setText("delete");
        deletesupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesupplierbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Enter Supplier ID to delete");

        deletesupplierIDtxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        deletesupplierIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesupplierIDtxtActionPerformed(evt);
            }
        });

        exitdeletesupplierbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        exitdeletesupplierbtn.setText("exit");
        exitdeletesupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitdeletesupplierbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitdeletesupplierbtn)
                        .addGap(153, 153, 153)
                        .addComponent(deletesupplierbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletesupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deletesupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitdeletesupplierbtn)
                    .addComponent(deletesupplierbtn))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletesupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesupplierbtnActionPerformed
        // Get supplier ID from input field
        String supplierID = deletesupplierIDtxt.getText().trim();

        // Validate input
        if (!supplierID.isEmpty()) {
            // Get the singleton instance of DataManager
            DataManager dataManager = DataManager.getInstance();

            // Check if the supplier exists
            if (dataManager.doesSupplierExist(supplierID)) {
                // Attempt to delete the supplier
                if (dataManager.deleteSupplier(supplierID)) {
                    // Display success message
                    JOptionPane.showMessageDialog(this, "Supplier deleted successfully:\n" +
                        "ID: " + supplierID, "Delete Success", JOptionPane.INFORMATION_MESSAGE);

                    // Clear input field
                    deletesupplierIDtxt.setText("");
                } else {
                    // Display error message if deletion fails (theoretically unlikely)
                    JOptionPane.showMessageDialog(this, "Failed to delete supplier.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                // Display error message if supplier ID does not exist
                JOptionPane.showMessageDialog(this, "Error: Supplier ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Display warning if the input field is empty
            JOptionPane.showMessageDialog(this, "Supplier ID field cannot be empty.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deletesupplierbtnActionPerformed

    private void deletesupplierIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesupplierIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletesupplierIDtxtActionPerformed

    private void exitdeletesupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitdeletesupplierbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SupplierEntryMenu().setVisible(true);
    }//GEN-LAST:event_exitdeletesupplierbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deletesupplierIDtxt;
    private javax.swing.JButton deletesupplierbtn;
    private javax.swing.JButton exitdeletesupplierbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
