/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import javax.swing.JOptionPane;

/**
 *
 * @author minam
 */
public class EditSupplier extends javax.swing.JFrame {

    /**
     * Creates new form EditSupplier
     */
    public EditSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entersedituppliercontacttxt = new javax.swing.JTextField();
        exiteditbtn1 = new javax.swing.JButton();
        entereditsupplierIDtxt = new javax.swing.JTextField();
        entereditsuppliernametxt = new javax.swing.JTextField();
        suppliereditsavebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entersedituppliercontacttxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        entersedituppliercontacttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entersedituppliercontacttxtActionPerformed(evt);
            }
        });

        exiteditbtn1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        exiteditbtn1.setText("exit");
        exiteditbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiteditbtn1ActionPerformed(evt);
            }
        });

        entereditsupplierIDtxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        entereditsupplierIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entereditsupplierIDtxtActionPerformed(evt);
            }
        });

        entereditsuppliernametxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        entereditsuppliernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entereditsuppliernametxtActionPerformed(evt);
            }
        });

        suppliereditsavebtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        suppliereditsavebtn.setText("save");
        suppliereditsavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliereditsavebtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter Supplier ID to edit");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter New Supplier Name");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Enter New Supplier Contact");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entereditsuppliernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entereditsupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entersedituppliercontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exiteditbtn1)
                        .addGap(153, 153, 153)
                        .addComponent(suppliereditsavebtn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(entereditsupplierIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(entereditsuppliernametxt)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(entersedituppliercontacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exiteditbtn1)
                    .addComponent(suppliereditsavebtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entersedituppliercontacttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entersedituppliercontacttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entersedituppliercontacttxtActionPerformed

    private void exiteditbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiteditbtn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new SupplierEntryMenu().setVisible(true);
    }//GEN-LAST:event_exiteditbtn1ActionPerformed

    private void entereditsupplierIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entereditsupplierIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entereditsupplierIDtxtActionPerformed

    private void entereditsuppliernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entereditsuppliernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entereditsuppliernametxtActionPerformed

    private void suppliereditsavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliereditsavebtnActionPerformed
        // 入力値を取得
        String supplierID = entereditsupplierIDtxt.getText().trim();
        String supplierName = entereditsuppliernametxt.getText().trim();
        String supplierContact = entersedituppliercontacttxt.getText().trim();

        // 入力バリデーション: 空白の入力がないか確認
        if (!supplierID.isEmpty() && !supplierName.isEmpty() && !supplierContact.isEmpty()) {
            // データを DataManager から更新
            DataManager dataManager = DataManager.getInstance(); // シングルトンインスタンスを取得
        
            System.out.println("Checking if supplier ID exists: " + supplierID);
            
            if (dataManager.doesSupplierExist(supplierID)) {
                
                Supplier supplier = dataManager.getSupplier(supplierID);
                System.out.println("Supplier found: ID = " + supplier.getId() + 
                        ", Name = " + supplier.getName() + 
                        ", Contact = " + supplier.getContact());
                // サプライヤー情報を更新
                if (dataManager.editSupplier(supplierID, supplierName, supplierContact)) {
                    // 更新成功メッセージを表示
                    JOptionPane.showMessageDialog(this, "Supplier updated successfully:\n" +
                        "ID: " + supplierID + "\n" +
                        "New Name: " + supplierName + "\n" +
                        "New Contact: " + supplierContact);
                    // 入力フィールドをクリア
                    entereditsupplierIDtxt.setText("");
                    entereditsuppliernametxt.setText("");
                    entersedituppliercontacttxt.setText("");
                } else {
                    // 更新失敗（理論上発生しない）
                    JOptionPane.showMessageDialog(this, "Failed to update supplier information.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                
                System.out.println("Supplier ID not found: "+ supplierID);
                
                // サプライヤーIDが存在しない場合のエラー
                JOptionPane.showMessageDialog(this, "Error: Supplier ID not found.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // 入力が不完全な場合
            JOptionPane.showMessageDialog(this, "All fields (ID, Name, Contact) must be filled.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_suppliereditsavebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entereditsupplierIDtxt;
    private javax.swing.JTextField entereditsuppliernametxt;
    private javax.swing.JTextField entersedituppliercontacttxt;
    private javax.swing.JButton exiteditbtn1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton suppliereditsavebtn;
    // End of variables declaration//GEN-END:variables
}
