/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import javax.swing.JOptionPane;

/**
 *
 * @author minam
 */
public class EditItem extends javax.swing.JFrame {
    
    //private static DataManager dataManager = new DataManager();
    private DataManager dataManager = DataManager.getInstance();

    /**
     * Creates new form EditItem
     */
    public EditItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editIDtxt = new javax.swing.JTextField();
        editnametxt = new javax.swing.JTextField();
        saveeditbtn = new javax.swing.JButton();
        exiteditbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter item ID to edit");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Enter new item name");

        editIDtxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        editIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIDtxtActionPerformed(evt);
            }
        });

        editnametxt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        editnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editnametxtActionPerformed(evt);
            }
        });

        saveeditbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        saveeditbtn.setText("save");
        saveeditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveeditbtnActionPerformed(evt);
            }
        });

        exiteditbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        exiteditbtn.setText("exit");
        exiteditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiteditbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exiteditbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveeditbtn)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(88, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveeditbtn)
                    .addComponent(exiteditbtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIDtxtActionPerformed

    private void editnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editnametxtActionPerformed

    private void exiteditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiteditbtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ItemManagement().setVisible(true);
    }//GEN-LAST:event_exiteditbtnActionPerformed

    private void saveeditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveeditbtnActionPerformed
        // TODO add your handling code here:                                            
        // Get input values
        String itemId = editIDtxt.getText().trim();
        String newItemName = editnametxt.getText().trim();

        // Check if item ID exists and attempt to edit
        if (!itemId.isEmpty() && !newItemName.isEmpty()) {
            if (dataManager.getInstance().doesItemExist(itemId)) { // Adjusted method name for clarity
                dataManager.editItem(itemId, newItemName);
                JOptionPane.showMessageDialog(this, "Item edited successfully: ID = " + itemId + ", New Name = " + newItemName);
            } else {
                JOptionPane.showMessageDialog(this, "Error: Item ID not found.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Item ID and new item name cannot be empty.");
        }
       
    }//GEN-LAST:event_saveeditbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editIDtxt;
    private javax.swing.JTextField editnametxt;
    private javax.swing.JButton exiteditbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton saveeditbtn;
    // End of variables declaration//GEN-END:variables
}
