/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;
import Administrator.*;
/**
 *
 * @author minam
 */
public class InventoryMenu extends javax.swing.JFrame {

    /**
     * Creates new form InventoryMenu
     */
    public InventoryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemmanagementbtn = new javax.swing.JButton();
        stockmanagementbtn = new javax.swing.JButton();
        suppliermanagementbtn = new javax.swing.JButton();
        addnewloginpasswordbtn = new javax.swing.JButton();
        mainexitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel1.setText("-- Inventory Manager Main Menu --");

        itemmanagementbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        itemmanagementbtn.setText("1. Item Management");
        itemmanagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmanagementbtnActionPerformed(evt);
            }
        });

        stockmanagementbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        stockmanagementbtn.setText("2. Stock Management");
        stockmanagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockmanagementbtnActionPerformed(evt);
            }
        });

        suppliermanagementbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        suppliermanagementbtn.setText("3. Supplier Management");
        suppliermanagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliermanagementbtnActionPerformed(evt);
            }
        });

        addnewloginpasswordbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        addnewloginpasswordbtn.setText("4. Add New Login Password");
        addnewloginpasswordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewloginpasswordbtnActionPerformed(evt);
            }
        });

        mainexitbtn.setText("Exit");
        mainexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainexitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addnewloginpasswordbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemmanagementbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stockmanagementbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suppliermanagementbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainexitbtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemmanagementbtn)
                .addGap(18, 18, 18)
                .addComponent(stockmanagementbtn)
                .addGap(18, 18, 18)
                .addComponent(suppliermanagementbtn)
                .addGap(18, 18, 18)
                .addComponent(addnewloginpasswordbtn)
                .addGap(35, 35, 35)
                .addComponent(mainexitbtn)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemmanagementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmanagementbtnActionPerformed
        // TODO add your handling code here:
        // Item Management Menu を表示
        new ItemManagement().setVisible(true);  // ItemManagement クラスのインスタンスを生成して表示
        this.dispose();  // 現在の InventoryMenu フレームを閉じる
    }//GEN-LAST:event_itemmanagementbtnActionPerformed

    private void mainexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainexitbtnActionPerformed
        this.dispose();
        login_page loginpage = new login_page();
        loginpage.setVisible(true);
    }//GEN-LAST:event_mainexitbtnActionPerformed

    private void stockmanagementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockmanagementbtnActionPerformed
        // TODO add your handling code here:
        new StockManagementMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stockmanagementbtnActionPerformed

    private void suppliermanagementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliermanagementbtnActionPerformed
        // TODO add your handling code here:
        new SupplierEntryMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suppliermanagementbtnActionPerformed

    private void addnewloginpasswordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewloginpasswordbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addnewloginpasswordbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewloginpasswordbtn;
    private javax.swing.JButton itemmanagementbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mainexitbtn;
    private javax.swing.JButton stockmanagementbtn;
    private javax.swing.JButton suppliermanagementbtn;
    // End of variables declaration//GEN-END:variables
}
