/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import javax.swing.JOptionPane;
import java.util.Map;

/**
 *
 * @author minam
 */
public class SupplierEntryMenu extends javax.swing.JFrame {

    /**
     * Creates new form SupplierEntryMenu
     */
    public SupplierEntryMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addsupplierbtn = new javax.swing.JButton();
        editsupplierbtn = new javax.swing.JButton();
        deletesupplierbtn = new javax.swing.JButton();
        viewsuppliersbtn = new javax.swing.JButton();
        supplierentryexitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel1.setText("-- Supplier Entry Menu --");

        addsupplierbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        addsupplierbtn.setText("1. Add Supplier");
        addsupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addsupplierbtnActionPerformed(evt);
            }
        });

        editsupplierbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        editsupplierbtn.setText("2. Edit Supplier");
        editsupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editsupplierbtnActionPerformed(evt);
            }
        });

        deletesupplierbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        deletesupplierbtn.setText("3. Delete Supplier");
        deletesupplierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletesupplierbtnActionPerformed(evt);
            }
        });

        viewsuppliersbtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        viewsuppliersbtn.setText("4. View Suppliers");
        viewsuppliersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsuppliersbtnActionPerformed(evt);
            }
        });

        supplierentryexitbtn.setText("Exit");
        supplierentryexitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierentryexitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(supplierentryexitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editsupplierbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addsupplierbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletesupplierbtn)
                            .addComponent(viewsuppliersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addsupplierbtn)
                .addGap(24, 24, 24)
                .addComponent(editsupplierbtn)
                .addGap(24, 24, 24)
                .addComponent(deletesupplierbtn)
                .addGap(18, 18, 18)
                .addComponent(viewsuppliersbtn)
                .addGap(29, 29, 29)
                .addComponent(supplierentryexitbtn)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addsupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addsupplierbtnActionPerformed
        // TODO add your handling code here:
        // Item Management Menu を表示
        new AddSupplier().setVisible(true);  // ItemManagement クラスのインスタンスを生成して表示
        this.dispose();  // 現在の InventoryMenu フレームを閉じる
    }//GEN-LAST:event_addsupplierbtnActionPerformed

    private void editsupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editsupplierbtnActionPerformed
        // TODO add your handling code here:
        new EditSupplier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editsupplierbtnActionPerformed

    private void deletesupplierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletesupplierbtnActionPerformed
        // TODO add your handling code here:
        new DeleteSupplier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deletesupplierbtnActionPerformed

    private void viewsuppliersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsuppliersbtnActionPerformed
        // TODO add your handling code here:
        // Get the singleton instance of DataManager
        DataManager dataManager = DataManager.getInstance();

        // Retrieve all suppliers from DataManager
        Map<String, Supplier> suppliers = dataManager.getAllSuppliers();

        // Prepare a message string to display supplier details
        if (!suppliers.isEmpty()) {
            StringBuilder message = new StringBuilder("Supplier List:\n");
            for (Map.Entry<String, Supplier> entry : suppliers.entrySet()) {
                Supplier supplier = entry.getValue();
                message.append("ID: ").append(supplier.getId())
                       .append(", Name: ").append(supplier.getName())
                       .append(", Contact: ").append(supplier.getContact())
                       .append("\n");
            }

            // Display supplier details in a message box
            JOptionPane.showMessageDialog(this, message.toString(), "Suppliers", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Display a message if no suppliers are stored
            JOptionPane.showMessageDialog(this, "No suppliers found.", "Suppliers", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_viewsuppliersbtnActionPerformed

    private void supplierentryexitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierentryexitbtnActionPerformed
        // TODO add your handling code here:
        new InventoryMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierentryexitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierEntryMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierEntryMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addsupplierbtn;
    private javax.swing.JButton deletesupplierbtn;
    private javax.swing.JButton editsupplierbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton supplierentryexitbtn;
    private javax.swing.JButton viewsuppliersbtn;
    // End of variables declaration//GEN-END:variables
}
