/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InventoryManager;

import javax.swing.JOptionPane;

/**
 *
 * @author minam
 */
public class UpdateStockLevel extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStockLevel
     */
    public UpdateStockLevel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enteritemIDforupdate = new javax.swing.JTextField();
        enteritemstocklevel = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        exitenteritembtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Enter Item ID (e.g., IT001)");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Enter Item Stock Level");

        enteritemIDforupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteritemIDforupdateActionPerformed(evt);
            }
        });

        enteritemstocklevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteritemstocklevelActionPerformed(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        exitenteritembtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        exitenteritembtn.setText("exit");
        exitenteritembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitenteritembtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enteritemstocklevel, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(enteritemIDforupdate))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(exitenteritembtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savebtn)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteritemIDforupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enteritemstocklevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(exitenteritembtn))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enteritemIDforupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteritemIDforupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteritemIDforupdateActionPerformed

    private void enteritemstocklevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteritemstocklevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteritemstocklevelActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        DataManager dataManager = DataManager.getInstance();
        
        // Get item ID and name from text fields
        String itemId = enteritemIDforupdate.getText().trim();
        String stockLevelInput = enteritemstocklevel.getText().trim();

        // Validate input
        if (!itemId.isEmpty() && !stockLevelInput.isEmpty()) {
            try {
                // アイテム数を整数に変換
                int stockLevel = Integer.parseInt(stockLevelInput);

                // 入力されたアイテムIDが存在するかチェック
                if (dataManager.doesItemExist(itemId)) {
                    // ストックレベルを更新
                    dataManager.updateStockLevel(itemId, stockLevel);
                    JOptionPane.showMessageDialog(this, "Stock level updated successfully: ID = " + itemId + ", Stock Level = " + stockLevel);
                    
                    // 入力フィールドをクリア
                    enteritemIDforupdate.setText("");
                    enteritemstocklevel.setText("");
                } else {
                    // アイテムIDが存在しない場合
                    JOptionPane.showMessageDialog(this, "Error: Item ID not found.");
                }
            } catch (NumberFormatException e) {
                // 入力が数値でない場合のエラーメッセージ
               JOptionPane.showMessageDialog(this, "Error: Stock level must be a valid number.");
            }
        } else {
            // 入力が空の場合のエラーメッセージ
            JOptionPane.showMessageDialog(this, "Item ID and Stock Level cannot be empty.");
        }

    }//GEN-LAST:event_savebtnActionPerformed

    private void exitenteritembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitenteritembtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new StockManagementMenu().setVisible(true);
    }//GEN-LAST:event_exitenteritembtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStockLevel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStockLevel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enteritemIDforupdate;
    private javax.swing.JTextField enteritemstocklevel;
    private javax.swing.JButton exitenteritembtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
