package PurchaseManager;

import javax.swing.JFrame;
import Administrator.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Shayvitha
 */
public class PMmenu extends javax.swing.JFrame {

    /**
     * Creates new form PMmenu
     */
    public PMmenu() {
        initComponents();
        setTitle("Purchase Manager Main Menu");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 450);  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listofitemsbtn = new javax.swing.JButton();
        listofsuppbtn = new javax.swing.JButton();
        purchaseorderbtn = new javax.swing.JButton();
        requisitionbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Purchase Manager Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(248, 46, 300, 32);

        listofitemsbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        listofitemsbtn.setText("List of Items");
        listofitemsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listofitemsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(listofitemsbtn);
        listofitemsbtn.setBounds(169, 148, 209, 39);

        listofsuppbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        listofsuppbtn.setText("List of Suppliers");
        listofsuppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listofsuppbtnActionPerformed(evt);
            }
        });
        getContentPane().add(listofsuppbtn);
        listofsuppbtn.setBounds(461, 148, 209, 39);

        purchaseorderbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        purchaseorderbtn.setText("Purchase Order");
        purchaseorderbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseorderbtnActionPerformed(evt);
            }
        });
        getContentPane().add(purchaseorderbtn);
        purchaseorderbtn.setBounds(169, 234, 209, 39);

        requisitionbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        requisitionbtn.setText("Requisition");
        requisitionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitionbtnActionPerformed(evt);
            }
        });
        getContentPane().add(requisitionbtn);
        requisitionbtn.setBounds(461, 234, 209, 39);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 310, 75, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listofitemsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listofitemsbtnActionPerformed
        this.dispose();
        
        GUI_Items listofitemspg = new GUI_Items();
        listofitemspg.setVisible(true);
        listofitemspg.setSize(700,600);
    }//GEN-LAST:event_listofitemsbtnActionPerformed

    private void listofsuppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listofsuppbtnActionPerformed
        this.dispose();
        
        GUI_Suppliers listofsupplierspg = new GUI_Suppliers();
        listofsupplierspg.setVisible(true);
        listofsupplierspg.setSize(700,600);
    }//GEN-LAST:event_listofsuppbtnActionPerformed

    private void purchaseorderbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseorderbtnActionPerformed
        this.dispose();
        
        JFrame requisitionFrame = new JFrame("Purchase Order Management");
        requisitionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        requisitionFrame.setContentPane(new GUI_PurchaseOrder());
        requisitionFrame.pack();
        requisitionFrame.setLocationRelativeTo(null);
        requisitionFrame.setVisible(true);
        requisitionFrame.setSize(1100,700);
        requisitionFrame.setLocation(0,0);
        
        
    }//GEN-LAST:event_purchaseorderbtnActionPerformed

    private void requisitionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitionbtnActionPerformed
        this.dispose();
        
        JFrame requisitionFrame = new JFrame("Requisition Management");
        requisitionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        requisitionFrame.setContentPane(new GUI_Requisition());
        requisitionFrame.pack();
        requisitionFrame.setLocationRelativeTo(null);
        requisitionFrame.setVisible(true);
        requisitionFrame.setSize(700,800);
        requisitionFrame.setLocation(0,0);
        
    }//GEN-LAST:event_requisitionbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        login_page loginpage = new login_page();
        loginpage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PMmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PMmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PMmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PMmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PMmenu().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listofitemsbtn;
    private javax.swing.JButton listofsuppbtn;
    private javax.swing.JButton purchaseorderbtn;
    private javax.swing.JButton requisitionbtn;
    // End of variables declaration//GEN-END:variables
}
